name: main
on:
  push:
    paths-ignore:
      - .github/**
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: development
    env:
      DATABRICKS_HOST: ${{ secrets.DEV_DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.DEV_DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Users/timsmith@codeplanes.info/DEV-DATABRICKS-GIT-FOLDER

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
    
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
    
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Repo (Dev)
        run: |
          databricks repos update "${{ env.REPO_PATH }}" --branch "${{ steps.extract_branch.outputs.branch }}"

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: production
    env:
      DATABRICKS_HOST: ${{ secrets.PROD_DEPLOYMENT_TARGET_URL }}
      DATABRICKS_TOKEN: ${{ secrets.PROD_DEPLOYMENT_TARGET_TOKEN }}
      REPO_PATH: /Workspace/Users/timsmith@codeplanes.info/PROD-DATABRICKS-GIT-FOLDER

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
    
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main
    
      - name: Extract branch name
        id: extract_branch_prod
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Update Databricks Repo (Prod)
        run: |
          databricks repos update "${{ env.REPO_PATH }}" --branch "${{ steps.extract_branch_prod.outputs.branch }}"
